### ISSUE TITLE
Documentation error: duplicate screenshot

### ISSUE THREAD

**Issue by ciberkleid** [repsyio/repsy-docs#1]
This section has the same screenshot twice:
https://docs.repsy.io/maven/using-private-maven-repository

The second screenshot should show the dependencies section of the pom.xml.

**Comment by firatkucuk** [comment]
Thanks @ciberkleid we'll update ASAP.

**Comment by firatkucuk** [comment]
We have fixed it and we will deploy it soon. Thanks for your contribution.
